runtime: python39
entrypoint: gunicorn main:app
service_account: sfl-tracker-app@appspot.gserviceaccount.com


handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto

# Configurações de escalabilidade para o nível gratuito
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0 # Permite escalar para zero instâncias quando não há tráfego (bom para o nível gratuito)
  max_instances: 1 # Para controlar custos, limita o número máximo de instâncias a 1.
